//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetUserPermission
    {
        public string UserId { get; set; }
        public string PermissionId { get; set; }
        public int Level { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        public virtual AspNetPermission AspNetPermission { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
