//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Email_handler_authent
    {
        public System.Guid AID { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string domainname { get; set; }
        public string status { get; set; }
    }
}
