//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Email_handler_log
    {
        public System.Guid EID { get; set; }
        public Nullable<System.Guid> UID { get; set; }
        public string Batch_ID { get; set; }
        public Nullable<System.DateTime> Insert_Date { get; set; }
        public string Message_ID { get; set; }
        public string Subject { get; set; }
        public string Email_Address_From { get; set; }
        public string Email_Address_To { get; set; }
        public string Attach_Filename { get; set; }
        public string Unique_Filename { get; set; }
        public string Event_Code { get; set; }
        public string Status { get; set; }
        public string Remarks { get; set; }
    }
}
