//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExportListenerSetting
    {
        public System.Guid Setting_PK { get; set; }
        public string FolderPath { get; set; }
        public string ExportType { get; set; }
        public string ExportLocation { get; set; }
        public string LoginName { get; set; }
        public string Password { get; set; }
        public string archive_folder { get; set; }
        public string EmailReceipent { get; set; }
        public string EmailSubject { get; set; }
        public string EmailContent { get; set; }
        public Nullable<bool> EmailAlert { get; set; }
        public string insert_user { get; set; }
        public System.DateTime insert_date { get; set; }
        public string update_user { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public Nullable<int> DelayTime { get; set; }
        public string FileNamePattern { get; set; }
        public string ExceptionFolder { get; set; }
        public Nullable<System.Guid> ExportTypeDetail_PK { get; set; }
        public Nullable<bool> IsEnabled { get; set; }
        public string FileExtension { get; set; }
        public Nullable<int> FileNamePatternSection { get; set; }
        public Nullable<bool> ExceptionAlert { get; set; }
        public string ExceptionReceipient { get; set; }
        public string ExceptionSubject { get; set; }
        public string ListenerType { get; set; }
    }
}
