//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExportTypeDetail
    {
        public System.Guid ExportTypeDetail_PK { get; set; }
        public string ExportTypeDetailName { get; set; }
        public string Description { get; set; }
        public string ExportLocation { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Flex1 { get; set; }
        public string Flex2 { get; set; }
        public string Flex3 { get; set; }
        public string Flex4 { get; set; }
        public string Flex5 { get; set; }
        public string insert_user { get; set; }
        public System.DateTime insert_date { get; set; }
        public string update_user { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
    }
}
