//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportListenerSetting
    {
        public System.Guid Setting_PK { get; set; }
        public string FolderPath { get; set; }
        public string JobName { get; set; }
        public string insert_user { get; set; }
        public Nullable<System.DateTime> insert_date { get; set; }
        public string update_user { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public string archive_folder { get; set; }
        public string EmailReceipent { get; set; }
        public string EmailSubject { get; set; }
        public string EmailContent { get; set; }
        public Nullable<bool> EmailAlert { get; set; }
        public string Mode { get; set; }
        public Nullable<int> Interval { get; set; }
        public Nullable<int> NumberOfRetry { get; set; }
        public Nullable<int> MaxToken { get; set; }
        public string SendFileTofolder { get; set; }
        public string SendFileToUserName { get; set; }
        public string SendFileToPassword { get; set; }
        public string FileNamePattern { get; set; }
        public Nullable<bool> IsRenameFileName { get; set; }
        public string ExceptionFolder { get; set; }
        public Nullable<int> FileNamePatternSection { get; set; }
        public Nullable<bool> IsEnabled { get; set; }
        public Nullable<bool> IsAutoMoveToException { get; set; }
        public Nullable<int> AutoMoveToExceptionNumberOfFileLimit { get; set; }
        public string FileExtension { get; set; }
        public string Description { get; set; }
        public Nullable<int> DelayTime_sec { get; set; }
        public bool IsRenameSendtoFilename { get; set; }
    }
}
