//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportListenerLog
    {
        public System.Guid ID { get; set; }
        public string FullFileName { get; set; }
        public Nullable<System.Guid> Setting_PK { get; set; }
        public string DIJobName { get; set; }
        public string ArchiveFullFileName { get; set; }
        public string Status { get; set; }
        public string insert_user { get; set; }
        public Nullable<System.DateTime> insert_date { get; set; }
        public Nullable<int> Seq { get; set; }
        public string SendToFullName { get; set; }
        public string SendToStauts { get; set; }
        public string ArchiveStatus { get; set; }
        public Nullable<System.Guid> GroupID { get; set; }
        public string Remark { get; set; }
        public string EventCode { get; set; }
        public Nullable<bool> IsEndPoint { get; set; }
    }
}
