//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEM_SysLog
    {
        public System.Guid SYS_PK { get; set; }
        public string SYS_LOG_Account { get; set; }
        public string SYS_Host { get; set; }
        public string SYS_Address { get; set; }
        public string SYS_Action { get; set; }
        public string SYS_Remarks { get; set; }
        public System.DateTime SYS_InsertDate { get; set; }
        public string SYS_InsertUser { get; set; }
    }
}
