//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TGF_DI_DataFile_Naming
    {
        public string MessageType { get; set; }
        public string CustID { get; set; }
        public string CustContain { get; set; }
        public int Seq { get; set; }
        public string DataType { get; set; }
        public string DataName { get; set; }
        public string Value { get; set; }
        public string DataFormat { get; set; }
        public string Description { get; set; }
        public string Flex1 { get; set; }
        public string Flex2 { get; set; }
        public string Flex3 { get; set; }
        public int naming_id { get; set; }
        public Nullable<int> naming_batch_id { get; set; }
        public Nullable<System.DateTime> Insert_date { get; set; }
        public string Insert_by { get; set; }
        public Nullable<System.DateTime> Update_date { get; set; }
        public string Update_by { get; set; }
        public string Status { get; set; }
    }
}
