//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TGF_THIRD_PARTY_EVENTS
    {
        public string CUSTOMER_NAME { get; set; }
        public string CARRIER_NAME { get; set; }
        public string KEY_REFERENCE { get; set; }
        public string SHIPMENT_GID { get; set; }
        public string MESSAGE_FORMAT { get; set; }
        public string EVENT_CODE { get; set; }
        public string EVENT_DATE { get; set; }
        public Nullable<System.DateTime> INSERT_DATE { get; set; }
        public string INPUT_FILE_NAME { get; set; }
        public string OUTPUT_FILE_NAME { get; set; }
        public string CONTROL_NUMBER { get; set; }
        public string VERSION_NUMBER { get; set; }
        public string BATCH_ID { get; set; }
        public string FTP_STATUS { get; set; }
        public Nullable<System.DateTime> START_DATE { get; set; }
        public Nullable<System.DateTime> END_DATE { get; set; }
        public string ICON_TRANS_ID { get; set; }
        public string ScriptPath { get; set; }
        public string BATFileName { get; set; }
        public Nullable<int> No_of_process { get; set; }
        public Nullable<System.DateTime> Reprocess_Datetime { get; set; }
        public string DI_Error_Details { get; set; }
        public string Remarks { get; set; }
        public string source_file_stream { get; set; }
        public string Order_No { get; set; }
        public string flex1 { get; set; }
        public string flex2 { get; set; }
        public string flex3 { get; set; }
        public string flex4 { get; set; }
        public string flex5 { get; set; }
        public string flex6 { get; set; }
        public string flex7 { get; set; }
        public string flex8 { get; set; }
        public System.Guid Event_PK { get; set; }
        public string DI_TraceLog_Details { get; set; }
        public string flex9 { get; set; }
        public string flex10 { get; set; }
        public string Process_Type { get; set; }
        public string Process_PK { get; set; }
        public string ALLOW_UPDATE { get; set; }
        public Nullable<bool> IsSendExportListener { get; set; }
    }
}
