//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Data.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TGF_IntegrationEntities : DbContext
    {
        public TGF_IntegrationEntities()
            : base("name=TGF_IntegrationEntities")
        {
        }
    
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Email_handler> Email_handler { get; set; }
        public virtual DbSet<Email_handler_authent> Email_handler_authent { get; set; }
        public virtual DbSet<Email_handler_log> Email_handler_log { get; set; }
        public virtual DbSet<ImportListenerLog> ImportListenerLog { get; set; }
        public virtual DbSet<ImportListenerSetting> ImportListenerSetting { get; set; }
        public virtual DbSet<ImportListenerStaging> ImportListenerStaging { get; set; }
        public virtual DbSet<ImportListenerToken> ImportListenerToken { get; set; }
        public virtual DbSet<ImportListenerVar> ImportListenerVar { get; set; }
        public virtual DbSet<ExportListenerSetting> ExportListenerSetting { get; set; }
        public virtual DbSet<ExportTypeDetail> ExportTypeDetail { get; set; }
        public virtual DbSet<TGF_GI_ControlTower_Logging> TGF_GI_ControlTower_Logging { get; set; }
        public virtual DbSet<TGF_GI_ControlTower_Server_Status_Setting> TGF_GI_ControlTower_Server_Status_Setting { get; set; }
        public virtual DbSet<ExportListenerLogShort> ExportListenerLogShort { get; set; }
        public virtual DbSet<TGF_THIRD_PARTY_EVENTS> TGF_THIRD_PARTY_EVENTS { get; set; }
        public virtual DbSet<TGF_GI_ControlTower_Alert_Log> TGF_GI_ControlTower_Alert_Log { get; set; }
        public virtual DbSet<TGF_PO_CONTROL_TABLE> TGF_PO_CONTROL_TABLE { get; set; }
        public virtual DbSet<ArchiveFolderSetting> ArchiveFolderSettings { get; set; }
        public virtual DbSet<TGF_DI_DataFile_Naming> TGF_DI_DataFile_Naming { get; set; }
    }
}
