//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TGF_GI_ControlTower_Server_Status_Setting
    {
        public System.Guid TGF_GI_ControlTower_Server_Status_Setting_PK { get; set; }
        public string Server_Name { get; set; }
        public string Type { get; set; }
        public string Setting_Detail { get; set; }
        public bool IsEnabled { get; set; }
        public string insert_user { get; set; }
        public System.DateTime insert_date { get; set; }
        public string update_user { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public string Display_Name { get; set; }
        public string Description { get; set; }
    }
}
