//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSetting
    {
        public System.Guid SettingID { get; set; }
        public string UserId { get; set; }
        public string Type { get; set; }
        public string DataType { get; set; }
        public string Value { get; set; }
    }
}
